//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWayAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class API_REPORTDBEntities1 : DbContext
    {
        public API_REPORTDBEntities1()
            : base("name=API_REPORTDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<MEMBERPROMO_Result> MEMBERPROMO(string dISTR)
        {
            var dISTRParameter = dISTR != null ?
                new ObjectParameter("DISTR", dISTR) :
                new ObjectParameter("DISTR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MEMBERPROMO_Result>("MEMBERPROMO", dISTRParameter);
        }
    }
}
