//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWayAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class API_REPORTDBEntities3 : DbContext
    {
        public API_REPORTDBEntities3()
            : base("name=API_REPORTDBEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<DISTR_RATIO_Result> DISTR_RATIO(string distr)
        {
            var distrParameter = distr != null ?
                new ObjectParameter("distr", distr) :
                new ObjectParameter("distr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DISTR_RATIO_Result>("DISTR_RATIO", distrParameter);
        }
    
        public virtual ObjectResult<NEW_MEMBERS_Result> NEW_MEMBERS(string distr)
        {
            var distrParameter = distr != null ?
                new ObjectParameter("distr", distr) :
                new ObjectParameter("distr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NEW_MEMBERS_Result>("NEW_MEMBERS", distrParameter);
        }
    }
}
